apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: C:\Users\lahou\scoop\apps\kompose\current\kompose.exe convert
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: python-app
  name: python-app
spec:
  ports:
    - name: "5001"
      port: 5001
      targetPort: 5000
  selector:
    io.kompose.service: python-app
